project:
  type: website
  output-dir: docs

website:
  page-footer:
    left: "Copyright 2022. HAL."
    right:
    - icon: github
      href: https://github.com
  title: "Hayley Lenamon"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - portfolio.qmd
      - walkthrough.qmd
      - usfppaper.qmd
      - Work.qmd
      - resume.qmd
      - Virginia.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true


